### ISSUE TITLE
Network connectivity

### ISSUE THREAD

**Issue by RustyJuice** [NiyaShy/XB1ControllerBatteryIndicator#11]
I noticed the application contacts a German server on first launch, couldn't see why it would require this in any of the documentation, is there a specific reason for this?

Cheers

**Comment by NiyaShy** [comment]
That should only happen when you ticked "check for new version on start" in the context menu. When the check is enabled, it loads an XML file (a copy of [this one](https://github.com/NiyaShy/XB1ControllerBatteryIndicator/blob/master/current_version.xml)) from my server to determine if there's a newer version available. 

I picked that route because I looked around how to best solve it and many said that accessing raw files directly from github can be a bit... unreliable...
