### ISSUE TITLE
Virus warnings "IDP.ALEXA.51"

### ISSUE THREAD

**Issue by Aganyur** [NiyaShy/XB1ControllerBatteryIndicator#12]
My Avast warned me about the .exe, says it would contain the above mentioned virus. 
Since I've already found some statements about this Virus being a false alarm in general, VirusTotal's 68 Scanners just return one generic result (even Avast doesn't detect anything) and this being an Open-Source-Project, I don't think that there really is an issue, but probably it's important to take a note of that. 
Windows SmartScreen doesn't want me to execute the program as well, but luckily that's overridable.
Using the latest testing version 1.2.1

Thanks for all your work!

**Comment by NiyaShy** [comment]
Thanks for letting me know. False positives can sadly happen any time, and I really can't think of why Avast would think it contains a malicious browser plugin... Also, as you said, since the source code is available here and anyone can build it themselves with visual studio there's really no point in trying to hide shady stuff in it.

And SmartScreen... it tends to flag anything that comes from the internet, plus the .exe is not signed, so that might be yet another reason for a false alarm.
