### ISSUE TITLE
Rechargeable Battery Level

### ISSUE THREAD

**Issue by videodj** [NiyaShy/XB1ControllerBatteryIndicator#13]
I have tried 2 sets of fully charged batteries and they only show as medium.  When I switch to some Duracell batteries they show as full.  Does it detect battery level differently for rechargeable batteries?

**Comment by NiyaShy** [comment]
Hey,
the program itself doesn't detect the battery level, it just displays what the controller reports. My guess would be that level detection is done via voltage levels since most batteries slowly drop in voltage as their charge goes down. Normal AA/AAA batteries have a regular voltage of 1.5V while rechargeables usually have "only" 1.2V. So that is probably why it only reports medium even though they are fully charged, because the start voltage is lower.
