### ISSUE TITLE
Tray icon hard to see on 1903 with the light theme

### ISSUE THREAD

**Issue by timocapa** [NiyaShy/XB1ControllerBatteryIndicator#23]
![Pic](https://user-images.githubusercontent.com/22844613/56508719-51147000-6525-11e9-8035-1c3f14faa7ce.png)

Maybe have it invert like Windows's own icons when the light mode is enabled? 

Otherwise seems to work without issues so far! :)

**Comment by illusive-man** [comment]
Totally disagree. What about Dark windows theme? Being inverted it will be like dark grey on black... Not sure that's good idea until there are two sets of icons for both modes.

**Comment by timocapa** [comment]
You misread my first sentence.

Windows inverts the system icons when switching themes.

See Ethernet and Audio icons
![a](https://user-images.githubusercontent.com/22844613/56516803-bf642d00-653b-11e9-8b9f-4e975b144ce8.gif)

**Comment by illusive-man** [comment]
I did. Sorry, my bad. )) In this case that would be awesome!

**Comment by NiyaShy** [comment]
Hey,
I see what you mean, but let me be honest, I never would have expected that anyone actually wants to use light mode... \*insert April fools joke about Discords light theme here\*
That the system-side icons switch is kind of to be expected, but I'm not sure if a program can even notice when the theme changes. And I also see that Discord avoided problems by adding a slight shadow/border around the icon.
When I find the time and motivation I'll see if I can edit the icons so they have a dark border for more contrast. But that will be 50 edits (25 icons x 2 resolutions)...

**Comment by timocapa** [comment]
> I see what you mean, but let me be honest, I never would have expected that anyone actually wants to use light mode... *insert April fools joke about Discords light theme here*
I, in fact, do prefer using light mode in most stuff throughout the day as I find it to be easier on the eyes. Night and everything is dark ;)

> That the system-side icons switch is kind of to be expected, but I'm not sure if a program can even notice when the theme changes
I'm not sure if the Auto Night Mode Switcher thing would help in reading the status? -> https://github.com/Armin2208/Windows-Auto-Night-Mode

**Comment by NiyaShy** [comment]
Hey,
since reworking all icons, especially the "old" 16x16 ones, would be a real PITA, I would instead opt for just removing the alpha channel (aka, transparency) from the icons and replacing their background with a solid color. Won't look as nice any more, but it should improve visibility in light theme.
Here's a test version where I replaced the "no controller found" icon with a version that has solid black as background.
[XB1ControllerBatteryIndicator_1.3.1_IconTest.zip](https://github.com/NiyaShy/XB1ControllerBatteryIndicator/files/3134513/XB1ControllerBatteryIndicator_1.3.1_IconTest.zip)

And about multiple instances: true, there's nothing that checks for that. But then again, running it more than once does no harm, the worst that could happen is that you get multiple low battery warnings. I looked into ways for preventing a second start, but they are... rather complicated...

**Comment by timocapa** [comment]
It, indeed, does not not look nice.
![image](https://user-images.githubusercontent.com/22844613/57026329-cd9c0280-6c39-11e9-88a4-cf2a214a4186.png)

**Comment by timocapa** [comment]
Inverting the icons isn't an issue and would only take a few minutes, but I don't know how to autochange the icon theme with Windows.

![image](https://user-images.githubusercontent.com/22844613/57027563-05f11000-6c3d-11e9-9ce7-9fd64065d0a6.png)

**Comment by timocapa** [comment]
Maybe this? https://stackoverflow.com/questions/51334674/how-to-detect-windows-10-light-dark-mode-in-win32-application

**Comment by timocapa** [comment]
inverted all icons (and layers)

https://github.com/timocapa/XB1ControllerBatteryIndicator/commit/c3a5b755fc3fc930b88a7d6dced9ae10f8a77870

![explorer_ZHMxt3y86C](https://user-images.githubusercontent.com/22844613/57031961-68e8a400-6c49-11e9-8c48-4957ded8eaa8.png)
![explorer_8dBI0cJIxL](https://user-images.githubusercontent.com/22844613/57031962-68e8a400-6c49-11e9-893d-865d8f11dfb9.png)

**Comment by NiyaShy** [comment]
Thanks, didn't think of inverting them. Your link goes in the right direction, but it seems to be for C++ while the program is written in C#. Something like [this](https://stackoverflow.com/questions/38734615/how-can-i-detect-windows-10-light-dark-mode) might work, I'll see what I can do.

**Comment by timocapa** [comment]
> Thanks, didn't think of inverting them.

Kein Problem 😄

> I'll see what I can do.

Danke :)

**Comment by NiyaShy** [comment]
One thing I'd need to know before I start to tinker: could you please check for me if a certain registry key changes when you switch between light and dark mode? I'm still running on 1809, so can't check it myself.
The key is under HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize and is called AppsUseLightTheme. 
I fear this key is "just" for the light/dark app mode that was implemented in (I think) one of the 180x releases, but not the actual light/dark theme switch. Since 1903 is still brand new I can barely find info about detecting the theme switch.

**Comment by timocapa** [comment]
There are two keys in that directory, AppsUseLightTheme and SystemUsesLightTheme

![RMmRgpvEmC](https://user-images.githubusercontent.com/22844613/57036205-e0233580-6c53-11e9-9b60-8983d618bcf1.gif)

**Comment by NiyaShy** [comment]
Ah, nice, so it seems to be SystemUsesLightTheme then. Don't have that key on 1809 yet. But since it's stored in the same place I should be able to tinker something together that works similar to detecting the light/dark app mode switch.

**Comment by timocapa** [comment]
Feel free to message me if you want me to test things

**Comment by NiyaShy** [comment]
Here you go, this test build should auto-detect the current theme and switch to the (non)inverted icons accordingly.
[XB1ControllerBatteryIndicator_1.3.1_LightThemeSwitch.zip](https://github.com/NiyaShy/XB1ControllerBatteryIndicator/files/3135837/XB1ControllerBatteryIndicator_1.3.1_LightThemeSwitch.zip)

**Comment by timocapa** [comment]
Not the fastest, but it certainly works!

![iCgUTkBmTN](https://user-images.githubusercontent.com/22844613/57039768-d7cff800-6c5d-11e9-90e4-1dc4a530c1a3.gif)

**Comment by NiyaShy** [comment]
Guess it's delayed because controller polling only happens every 1-5 seconds and that's currently what changes the icon, so it only updates after the next poll is finished. I'll tinker some more, at least we're getting there ;)

**Comment by timocapa** [comment]
Good to know, I guess - Thanks! I think I can close this now? :)
