### ISSUE TITLE
Elite v2 controller support

### ISSUE THREAD

**Issue by roobre** [NiyaShy/XB1ControllerBatteryIndicator#32]
Hello,

Thanks for your work and effort on this project, it's very useful!
I wonder if Elite v2 controller is supported. I can tell is detected, but it reports the battery being "Full" no matter how long I play. I haven't checked if this behavior sticks until the battery depletes completely, but I'd say I should have seen more states by now.

Has this been tested against the Elite v2 controller? If not, is there anything I can do to help? I'm not very fluent in C# but the codebase does not seem too complex, so maybe I can give it a try.

Regards!

**Comment by NiyaShy** [comment]
Hey,
as long as it detects a battery level it should work with the Elite v2, but so far I got no feedback on it. Guess not many want to sink so much money into a controller 😉 

I can just say from my experience with "normal" XBOne controllers that it can easily take a week or 2 (with ~2-4 hours of playing each day) until the battery level changes. 
There shouldn't be any coding necessary to support it since any XBox-ish controller can be polled via XInput and should report a decently accurate battery level. But help with coding and suggestions are always welcome nonetheless 😃

**Comment by roobre** [comment]
Thanks for your response!
I got a bit carried away by the "40 hours of gameplay" advertised battery life. After a while the indicator has indeed dropped from Full to Medium, so it looks like it's working nicely.
Thanks again for your efforts on this!
