### ISSUE TITLE
Play & charge kit

### ISSUE THREAD

**Issue by Gamesiarz** [NiyaShy/XB1ControllerBatteryIndicator#4]
Tray icon doesn't detect properly status when we are charging via play and charge kit. Xbox accessories app detect it.

**Comment by NiyaShy** [comment]
What exactly do you mean? That it doesn't show that the controller is charging?
If so, that is correct. It doesn't care if the controller is charging or not, just if it's present and what the current battery level is. 
I looked through the documentation of the library/API that is used to collect the battery level and couldn't see if there is even a way to detect charging. 
Since Microsoft developed both the hardware and the software/API they have a lot more knowledge about what can be collected, so that's probably why the accessories app knows when it's charging.

Then again, does it even matter if it can detect the charging state? When you're using the official play&charge cable you have the status LED on the plug.
