### ISSUE TITLE
Now that Windows 10 has focus assist, how can I make an exception for this app?

### ISSUE THREAD

**Issue by Jimmytbane** [NiyaShy/XB1ControllerBatteryIndicator#40]
The app is not registered in the list of possible exceptions for focus assist. I think I can use the sound to warn me but the notification would be more helpful

**Comment by NiyaShy** [comment]
Uh, not 100% sure what you mean since I don't have an English version of windows at hand. If you mean the notification assistant that lets you suppress toast messages during certain times or while you're gaming/running something in fullscreen, it should be listed there (at least it is on my system). 
![](https://i.imgur.com/o0Jv9Vd.png)

I know that some ppl had the issue that they didn't get a toast even though it wasn't blocked, that's one of the reasons why the extra notification sound was added. But those reports were quite a while ago, maybe even before focus assist was added.

Also, the toast is classified as a "reminder", which is (according to Microsofts documentation) slightly below the "alarm" tier but should still count as a priority notification.

**Comment by JimmyByte** [comment]
Turns out I just had to actually try it and it works and the notification shows up thru “focus assist”(English term)

**Comment by NiyaShy** [comment]
There's not really anything you have to "set up". On first start it should register itself to the start menu (that's required for being allowed to send toasts), after that all configuration is done via the context menu.
