### ISSUE TITLE
Jostyck ps4 

### ISSUE THREAD

**Issue by matropiero** [NiyaShy/XB1ControllerBatteryIndicator#41]
Hey dude!
I wanted to ask a question. Since I have a jostyck ps4 and it does not recognize it when I use the application. This connects via bluetooh without problems to windows.
Sorry if this is not the correct option, I just wanted to consult.
Thank you.

**Comment by NiyaShy** [comment]
Hey,
the problem is AFAIK (don't own any PS4 stuff) that PS4 controllers use a different "protocol" to talk to the console or your PC. This program only understands/can work with controllers that use XInput which is used by xbox-ish controllers.

So, due to that difference, it won't work with PS4 controllers.
