### ISSUE TITLE
Notification for low battery, not just empty 

### ISSUE THREAD

**Issue by stealthrabbi** [NiyaShy/XB1ControllerBatteryIndicator#44]
When the battery is almost empty, that may not be enough time to get new batteries. Can you give the option to allow for warning at low?

**Comment by NiyaShy** [comment]
Hey,
have you actually experienced this (that the battery was completely flat shortly after the warning)? 
I've so far only worked with the "official" battery packs, not with normal or rechargeable batteries, and they have a "grace period" of about 10-15 minutes before the controller shuts off. 

Also, getting a note on low state shouldn't be that useful since it can happen hours before the battery (pack) is even close to going flat...

**Comment by stealthrabbi** [comment]
Sorry, was making an assumptin about the behavior. Just drained my batteries for the first time, and I had enough time to swap batteries out. But, I didn't get any notice besides the sound. Is it suppose to have a balloon / popup of some kind?

**Comment by NiyaShy** [comment]
Hey,

as the screenshots on the main page show, you should get a so-called "toast", the typical notification windows in the bottom right that Win10 uses. But if you're running a game/program in fullscreen Win10 apparently sometimes suppresses that window. That's why the separate warning sound (and the option to loop it) was added.
