### ISSUE TITLE
Latest release picked up by Windows Defender as a trojan

### ISSUE THREAD

**Issue by pabsi** [NiyaShy/XB1ControllerBatteryIndicator#58]
**Please note despite my folder name (1.2.0) this is the latest release (1.3.1)**.

See screenshot below:

![image](https://user-images.githubusercontent.com/5247611/121804871-c8974300-cc48-11eb-9cc0-b01b5c68069e.png)

I (want to) assume this is a false positive.

Thank you!

**Comment by pabsi** [comment]
Note: it seems this is reported in other github repos too as false positive:
https://www.google.com/search?q=emali+a!cl

Not sure if the codeowner can do anything about it? If not, please close the issue.

Thank you again!

**Comment by NiyaShy** [comment]
Thanks for the notification. Didn't notice myself since I'm already running the (pre-release version of) 1.4 that isn't detected.

Interestingly enough, I ran the [current 1.3.1](https://www.virustotal.com/gui/file/a4b0607b0e36c09179f422837a3662e53cccc8d80b00902d8ecf452bc1ed5c25/detection) with all submitted languages, a [slightly older version](https://www.virustotal.com/gui/file/57c13f3c38667aecb6336d6b069d271c7b5e662aff8adce9c8bf4f4aa811d045/detection) I still had around, and the [1.4 pre-release](https://www.virustotal.com/gui/file/57eff48d339cf3745eba88a7b10c18f35f33904289a69a535e062c4a8dc41ca4/detection) through Virustotal and only the latest 1.3.1 got flagged by Microsoft... All 3 were reported by MalwareBytes and MaxSecure, though those should be false positives as well.

Anyway, just submitted it to Microsoft as a false positive. Apparently their online/cloud scanner detects it as Backdoor:Win32/Bladabindi!ml. We'll see if/when I get a reply.

**Comment by pabsi** [comment]
Ah, thanks for such speedy response!! Hugely appreciated.

And thank you for this really useful piece of software :)

All the best!

**Comment by NiyaShy** [comment]
Got a reply from Microsoft, the false positive should be fixed with updated AV patterns for Windows Defender. Tried it myself and it seems to work again.

Thank you for the report (as I mentioned, wouldn't have noticed myself), and great to hear that you're happy with it 😃
