### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by lmills87** [NiyaShy/XB1ControllerBatteryIndicator#59]
1. It would be great if there was an easy way to turn the controller off in the system tray options. Oftentimes I hold the button down (to turn the controller off) and it messes up and starts syncing or something, and then the only apparent way to turn it off is to rip the battery out (which I prefer not doing). It would just safe time and headache overall if I could simply right-click the system tray icon and then click "turn controller off" or something similar.

2. This is kind of pedantic and just an aesthetic suggestion, but it would be nice to see "Shut up!" changed to "Silence" or "Silence alerts" or something of that nature.

**Comment by NiyaShy** [comment]
Hey,
turning the controller off via software is, as far as I know, not possible. XInput has no way to tell the controller to do that.

And renaming the button text would be possible, but once 1.4 hits and the new overlay spreads more I guess many will turn the toast notifications off anyway (since they apparently can cause issues like focus loss for games). I might consider it since I have to round up the translation creators for 1.4 anyway, but consider it a VERY low priority.

**Comment by lmills87** [comment]
That's too bad, would be so great to be able to turn it off. Well something that I have noticed is that my controller turns off when I quit certain games. I'm not sure how that's occurring but perhaps that behavior could be mimicked in some way?

**Comment by Zer01neDev** [comment]
Would be cool to add support of Xbox Wireless Headset and send a Audio request just before it turns off.
