### ISSUE TITLE
Spybot reports the start menu link as Fraud-000

### ISSUE THREAD

**Issue by axemwa** [NiyaShy/XB1ControllerBatteryIndicator#61]
Hey there I love your program it's amazing and works really well just thought I'd let you know that Spybot has reported your program as a mid-level threat as a malware known as "Fraud-000" with the filename as "XB1ControllerBatteryIndicator.lnk". I'm sure it's nothing but I just thought I'd mention it incase you didn't know and incase you could prove to spybot devs that it's not a threat if you wanted to that is. Plus it looks like the "XB1ControllerBatteryIndicator.lnk" was only there so that it could start with windows instead of the user having to start it everytime. Anyway that's all I had to say I'm sure they got it wrong anywho hope u have a great one take care :)

PS: Here's a link to a snapshot of the report if you wanted to see it.
https://imgur.com/a/5I4Mm0E

**Comment by NiyaShy** [comment]
Hey,
thanks for the note. It's 100% a false positive.

The reason why the lnk file is created is a bit different. According to Microsofts documentation any program that wants to send toast notifications **has** to create a link to itself in the start menu. That's why you aren't asked if you want the entry added, it happens automatically on first start.

Fraud-000 sounds like it wasn't a specific pattern but most likely heuristics (aka, something looked suspicious).

Tried to look up how you can report false positives to Spybot (you mean S&D, right?), and it seems the only way is to post on their [forums](https://forums.spybot.info/forumdisplay.php?16-False-Positives).
