### ISSUE TITLE
No battery data after FW update

### ISSUE THREAD

**Issue by nfraihat** [NiyaShy/XB1ControllerBatteryIndicator#63]
I updated my Xbox One controller (with headphone jack) to the latest firmware. No battery info is being reported.

I'm getting this message: Found but still waiting for battery data

FW: 5.13.3143.0

**Comment by NiyaShy** [comment]
Hey, sad to hear that you have issues. Just in case so I might be able to cross-check, could you tell me the model number as well? (on the label in the battery compartment, might be in a really tiny font). 
Just tried with my XBOne controller (model 1697) freshly updated to FW 2.3.2385.0 and it still works fine.

Judging by the high FW number on yours, is it a series X/S controller (model 1914)? Can cross-check that one tomorrow...

**Comment by nfraihat** [comment]
Hey, it's a Model 1708.

**Comment by NiyaShy** [comment]
K, yours must be an in-between model then, I only have 1697 (first XBOne with a normal headphone jack) and the newer Series X (1914) with the hybrid D pad. But after just checking the latter, it updated to the same FW version as yours and is still properly recognized.
Are you using one of the proprietary dongles MS offers or Bluetooth? Because the latter has massive issues as you can read in issue #49.

Other than that I can't do much about it. The polling should work for any xbox-ish controller, but it can sometimes take a while for initial contact to happen.

**Comment by NiyaShy** [comment]
Many hope it gets fixed soon, but since nothing has happened for over a year now it's rather unlikely...
Anyway, since you (also) have the BT issue, I'll take the liberty to close this issue.
