### ISSUE TITLE
Battery Indicator as Widget

### ISSUE THREAD

**Issue by CptnJaxx** [NiyaShy/XB1ControllerBatteryIndicator#77]
Hello there!
Is there a way this can be made into a rainmeter widget? Or is there any other way to make the battery level visible besides it beeing only shown in the system tray?
Thanks in advance!

**Comment by NiyaShy** [comment]
Hey,
it's probably possible, but I have no experience with if/how Rainmeter can interact with other programs. And since the battery levels only change very rarely I don't see that much value in seeing it all the time, especially since you probably don't see your desktop that much during gaming and have the controller turned off otherwise 😉
