### ISSUE TITLE
Tray icon gets invisible as soon as a battery status is detected

### ISSUE THREAD

**Issue by grimsi** [NiyaShy/XB1ControllerBatteryIndicator#9]
The software seems to work fine for the first few seconds (showing a tray icon with the text "Controller One detected but still waiting for battery status").
But I guess as soon as it detects the battery status the icon gets invisible (the software is still running when I check in Task Manager).
Im using the newest Windows 10 Pro N Version, a Xbox One S controller with the first dongle and without battery pack (if that matters).
The options "start with windows" and "check for updates on startup" are activated.

**Comment by NiyaShy** [comment]
Hmm... Interesting. When you say invisible, is the systray spot still occupied (so, can you still access the right click menu), or does it entirely vanish?
Another thing that windows loves to do is to move systray icons to the "overflow" menu (the little white arrow that expands the systray area to show everything). You can prevent that by dragging the icon to any position with your mouse, that will "lock" it in that spot.

**Comment by grimsi** [comment]
Thanks for the fast response :)
It vanishes completly and does not block the spot any longer. I also checked the overflow menu but it didnt appear there. Its just gone.
Also the XBOX Accessory App detects the status correctly. Maybe it has something to do with the system language (german in my case)?

**Comment by NiyaShy** [comment]
Language doesn't affect it, I'm running a German windows installation too 😛 Though I'm still running on 1803 (when you say "newest", you mean the just released 1809, right?)
One thing that would be interesting to know: you said it vanishes when it switches from "found controller but no data yet" to battery level display. Does that mean the initial switch from "no controller found" to "no data yet" works without it vanishing? That would be really weird since all icon changes work the same way, so if the first switch works but every subsequent lets it vanish, that's... strange...

**Comment by grimsi** [comment]
It works now. I didnt change anything I just restarted a few times...
But yes im running 1809 and yes the initial switch did work. I guess Windows was guilty here

**Comment by NiyaShy** [comment]
K, good to know that it resolved itself. I just hope that it's not some weird glitch they introduced with 1809... Could you keep an eye on if it happens again in the next days?

**Comment by grimsi** [comment]
Sure, I'll tell you when I see something strange happening

**Comment by NiyaShy** [comment]
Did you notice any more weird behaviour in the last weeks? If not i'd close the issue.
